# Generated by Django 5.2.10 on 2026-02-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
