# Generated by Django 5.2.10 on 2026-02-02 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0003_alter_inbounditem_expected_quantity"),
        ("orders", "0002_alter_reservation_expires_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Shopping Cart",
                "verbose_name_plural": "Shopping Carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Cart Item",
                "verbose_name_plural": "Cart Items",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Inventory Reservation",
                "verbose_name_plural": "Inventory Reservations",
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Cart expiration time for cleanup", null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session identifier for guest carts",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="User identifier for authenticated users",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price per unit at time of adding to cart",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.variant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.JSONField(help_text="Billing address details"),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="EUR", help_text="ISO 4217 currency code", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(
                help_text="Customer email for order notifications", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Customer user ID if authenticated",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total discount amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="Customer IP address at order creation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, help_text="Customer or internal notes"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                db_index=True,
                help_text="Human-readable order number",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, help_text="Payment method used", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="External payment reference/transaction ID",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("authorized", "Authorized"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(help_text="Shipping address details"),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Shipping cost",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("ready_to_ship", "Ready to Ship"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Subtotal before tax and shipping",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total tax amount",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Final total amount",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user_agent",
            field=models.TextField(blank=True, help_text="Customer user agent string"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount applied to this item",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(help_text="SKU at time of order", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Tax amount for this item",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Tax rate applied",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total price for this line item",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Unit price at time of order",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                help_text="Product variant ordered",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.variant",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Variant attributes at time of order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_name",
            field=models.CharField(
                help_text="Product/variant name at time of order", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="warehouse",
            field=models.ForeignKey(
                help_text="Warehouse fulfilling this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="inventory.warehouse",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration time for pending reservations",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata (IP, user agent, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_token",
            field=models.CharField(
                db_index=True,
                help_text="Unique token for this reservation",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("consumed", "Consumed by Order"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="catalog.variant",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="inventory.warehouse",
            ),
        ),
    ]
