# Generated by Django 5.2.10 on 2026-02-02 11:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0003_alter_inbounditem_expected_quantity"),
        ("orders", "0003_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="orders_cart_cart_id_02c352_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_order_n_f3ada5_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_59b6fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_custome_ca0107_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_c6dd84_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_payment_bc131d_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_0e92de_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_order_i_c8de3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_sku_737ca0_idx",
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="orders_rese_reserva_953162_idx",
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="orders_rese_variant_b77ae0_idx",
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="orders_rese_status_c4dc34_idx",
        ),
        migrations.RemoveIndex(
            model_name="reservation",
            name="orders_rese_expires_bc57d7_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_reference",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_agent",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="tax_rate",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant_attributes",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="session_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.variant"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.variant"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.warehouse"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_token",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.variant"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.warehouse"
            ),
        ),
    ]
