# Generated by Django 5.2.10 on 2026-02-02 13:36

import apps.orders.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("inventory", "0003_alter_inbounditem_expected_quantity"),
        ("orders", "0004_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["order", "created_at"],
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_token",
            field=models.CharField(
                db_index=True,
                default=apps.orders.models.generate_reservation_token,
                editable=False,
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_id"], name="orders_orde_custome_59b6fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="orders_orde_created_0e92de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["reservation_token"], name="orders_rese_reserva_953162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["status"], name="orders_rese_status_c4dc34_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["expires_at"], name="orders_rese_expires_bc57d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["variant", "warehouse"], name="orders_rese_variant_b77ae0_idx"
            ),
        ),
    ]
