# Generated by Django 5.2.10 on 2026-02-05 11:42

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_orderitem_options_alter_reservation_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_token",
            field=models.CharField(
                db_index=True,
                default=apps.orders.models.generate_reservation_token,
                editable=False,
                max_length=100,
            ),
        ),
    ]
