# Generated by Django 5.2.10 on 2026-02-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idempotencykey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Idempotency Key",
                "verbose_name_plural": "Idempotency Keys",
            },
        ),
        migrations.AlterModelOptions(
            name="scheduledjob",
            options={
                "ordering": ["scheduled_at"],
                "verbose_name": "Scheduled Job",
                "verbose_name_plural": "Scheduled Jobs",
            },
        ),
    ]
