# Generated by Django 5.2.10 on 2026-02-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0002_alter_idempotencykey_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IdempotencyKey",
        ),
    ]
