# Generated by Django 5.2.10 on 2026-01-29 23:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('channel', models.CharField(blank=True, choices=[('web', 'Web'), ('app', 'Mobile App'), ('marketplace', 'Marketplace'), ('retail', 'Retail Store'), ('wholesale', 'Wholesale')], max_length=50)),
                ('customer_group', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('vip', 'VIP'), ('employee', 'Employee'), ('b2b', 'B2B')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='pricing_pri_code_830d69_idx'), models.Index(fields=['country', 'channel', 'customer_group'], name='pricing_pri_country_7b894f_idx'), models.Index(fields=['is_active'], name='pricing_pri_is_acti_04500d_idx'), models.Index(fields=['is_default'], name='pricing_pri_is_defa_02eb34_idx')],
                'unique_together': {('country', 'channel', 'customer_group')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tax_class', models.CharField(default='standard', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'state', '-effective_from'],
                'indexes': [models.Index(fields=['country', 'state', 'tax_class'], name='pricing_tax_country_4fa455_idx'), models.Index(fields=['is_active'], name='pricing_tax_is_acti_10aae6_idx'), models.Index(fields=['effective_from', 'effective_to'], name='pricing_tax_effecti_f987c2_idx')],
                'unique_together': {('country', 'state', 'tax_class', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='PriceBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='pricing.pricebook')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.variant')),
            ],
            options={
                'verbose_name_plural': 'Price book entries',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['price_book', 'variant'], name='pricing_pri_price_b_1af9c3_idx'), models.Index(fields=['price_book', 'product'], name='pricing_pri_price_b_d79447_idx'), models.Index(fields=['price_book', 'category'], name='pricing_pri_price_b_7431db_idx'), models.Index(fields=['effective_from', 'effective_to'], name='pricing_pri_effecti_b61b7b_idx'), models.Index(fields=['price'], name='pricing_pri_price_b00dcb_idx')],
            },
        ),
    ]
