# Generated by Django 5.2.10 on 2026-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricebook",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, unique=True
            ),
        ),
    ]
