# Generated by Django 5.2.10 on 2026-02-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_alter_pricebook_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricebook",
            name="channel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("web", "Web"),
                    ("app", "Mobile App"),
                    ("mobile", "Mobile"),
                    ("marketplace", "Marketplace"),
                    ("retail", "Retail Store"),
                    ("wholesale", "Wholesale"),
                ],
                max_length=50,
            ),
        ),
    ]
