# Generated by Django 5.2.10 on 2026-01-29 23:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('priority', models.IntegerField(default=10, help_text='Higher number = higher priority')),
                ('is_active', models.BooleanField(default=True)),
                ('stacking_type', models.CharField(choices=[('none', 'No Stacking - Highest Priority Wins'), ('all', 'Stack All Eligible'), ('exclusive', 'Exclusive - Only This Campaign'), ('combined', 'Combine with Specific Campaigns')], default='none', max_length=20)),
                ('max_discount_per_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_groups', models.JSONField(blank=True, default=list)),
                ('excluded_customer_groups', models.JSONField(blank=True, default=list)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum number of times this campaign can be used', null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'start_at'],
                'indexes': [models.Index(fields=['code'], name='promotions__code_fc3bfd_idx'), models.Index(fields=['start_at', 'end_at'], name='promotions__start_a_0067c9_idx'), models.Index(fields=['priority'], name='promotions__priorit_00901f_idx'), models.Index(fields=['is_active'], name='promotions__is_acti_a9432d_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed_amount', 'Fixed Amount Off'), ('price_override', 'Price Override'), ('tiered', 'Tiered Discount'), ('bogo', 'Buy X Get Y')], default='percentage', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('applies_to', models.CharField(choices=[('variant', 'Per Variant'), ('product', 'Per Product'), ('category', 'Per Category'), ('order', 'Entire Order')], default='variant', max_length=20)),
                ('tier_rules', models.JSONField(blank=True, default=list, help_text="For tiered discounts: [{'min_quantity': 5, 'discount': 10}, ...]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'min_quantity'],
                'indexes': [models.Index(fields=['campaign', 'discount_type'], name='promotions__campaig_b8531c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('product', 'Product'), ('variant', 'Variant'), ('category', 'Category'), ('brand', 'Brand'), ('attribute', 'Attribute'), ('collection', 'Collection')], max_length=20)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('in', 'In List'), ('not_in', 'Not In List'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('between', 'Between')], default='equals', max_length=20)),
                ('value', models.TextField(help_text='Value to match against')),
                ('scope', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], default='include', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Order of evaluation')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='promotions.campaign')),
            ],
            options={
                'ordering': ['campaign', 'order'],
                'indexes': [models.Index(fields=['campaign', 'rule_type'], name='promotions__campaig_4e3eba_idx')],
            },
        ),
    ]
