# Generated by Django 5.2.10 on 2026-02-01 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={},
        ),
        migrations.AlterModelOptions(
            name="campaigndiscount",
            options={},
        ),
        migrations.AlterModelOptions(
            name="campaignrule",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="promotions__code_fc3bfd_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="promotions__start_a_0067c9_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="promotions__priorit_00901f_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaign",
            name="promotions__is_acti_a9432d_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaigndiscount",
            name="promotions__campaig_b8531c_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaignrule",
            name="promotions__campaig_4e3eba_idx",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="customer_groups",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="excluded_customer_groups",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="max_discount_per_order",
        ),
        migrations.RemoveField(
            model_name="campaigndiscount",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="campaigndiscount",
            name="min_price",
        ),
        migrations.RemoveField(
            model_name="campaigndiscount",
            name="tier_rules",
        ),
        migrations.RemoveField(
            model_name="campaigndiscount",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="priority",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="stacking_type",
            field=models.CharField(
                choices=[
                    ("none", "No Stacking"),
                    ("all", "Stack All"),
                    ("exclusive", "Exclusive"),
                    ("combined", "Combined"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="usage_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaigndiscount",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("line_item", "Line Item"),
                    ("order", "Order"),
                    ("shipping", "Shipping"),
                ],
                default="line_item",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaigndiscount",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_amount", "Fixed Amount"),
                    ("price_override", "Price Override"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaigndiscount",
            name="value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="operator",
            field=models.CharField(
                choices=[("equals", "Equals"), ("in", "In"), ("between", "Between")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("variant", "Variant"),
                    ("category", "Category"),
                    ("brand", "Brand"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="scope",
            field=models.CharField(
                choices=[("global", "Global"), ("line_item", "Line Item")],
                default="global",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="campaignrule",
            name="value",
            field=models.TextField(),
        ),
    ]
