# Generated by Django 5.2.10 on 2026-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_pricebook_alter_campaign_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="code",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
