# Generated by Django 5.2.10 on 2026-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0005_campaigndiscount_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrule",
            name="action",
            field=models.CharField(
                choices=[("include", "Include"), ("exclude", "Exclude")],
                default="include",
                max_length=20,
            ),
        ),
    ]
