# Generated by Django 5.2.10 on 2026-02-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_campaignrule_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("product", "Product"),
                    ("variant", "Variant"),
                    ("category", "Category"),
                    ("brand", "Brand"),
                    ("attribute", "Attribute"),
                ],
                max_length=20,
            ),
        ),
    ]
