# Generated by Django 5.2.10 on 2026-01-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundshipment",
            name="expected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inboundshipment",
            name="reference",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="code",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
