# Generated by Django 5.2.10 on 2026-01-31 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inboundshipment_expected_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbounditem",
            name="expected_quantity",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
