# Generated by Django 5.2.10 on 2026-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inbounditem_expected_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbounditem",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
