# Generated by Django 5.2.10 on 2026-01-29 23:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pricing', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.UUIDField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.campaign')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['campaign', 'changed_at'], name='audit_campa_campaig_eefd11_idx'), models.Index(fields=['changed_field'], name='audit_campa_changed_2c7c80_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('adjustment', 'Manual Adjustment'), ('reservation', 'Reservation'), ('release', 'Reservation Release'), ('fulfillment', 'Order Fulfillment'), ('receipt', 'Inbound Receipt'), ('transfer', 'Warehouse Transfer'), ('write_off', 'Write Off'), ('correction', 'Correction')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('from_quantity', models.IntegerField(blank=True, null=True)),
                ('to_quantity', models.IntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.variant')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'created_at'], name='audit_inven_variant_c5134f_idx'), models.Index(fields=['event_type', 'created_at'], name='audit_inven_event_t_e07439_idx'), models.Index(fields=['reference'], name='audit_inven_referen_ba2005_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('changed_by', models.UUIDField(blank=True, help_text='User ID who made the change', null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('price_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.pricebook')),
                ('price_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricebookentry')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.variant')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['variant'], name='audit_price_variant_7ff639_idx'), models.Index(fields=['price_book'], name='audit_price_price_b_43944b_idx'), models.Index(fields=['changed_at'], name='audit_price_changed_ced0a6_idx')],
            },
        ),
    ]
