# Generated by Django 5.2.10 on 2026-02-05 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "request_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA256 hash of request",
                        max_length=64,
                    ),
                ),
                ("request_path", models.CharField(blank=True, max_length=255)),
                ("response_code", models.IntegerField(null=True)),
                ("response_body", models.JSONField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["key"], name="audit_idemp_key_39b09e_idx"),
                    models.Index(
                        fields=["status"], name="audit_idemp_status_3ce703_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="audit_idemp_expires_af6593_idx"
                    ),
                ],
            },
        ),
    ]
