# Generated by Django 5.2.10 on 2026-02-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("discontinued", "Discontinued"),
                    ("out_of_season", "Out of Season"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
